In [1]:
import pandas as pd
import numpy as np

In [70]:
%cd /home/dsc/Ejer

/home/dsc/Ejer

In [71]:
#Importamos dataset del Ministerio Industria sobre precios diarios de Gasolineras
#http://geoportalgasolineras.es/#/Descargas

df = pd.read_excel('preciosEESS_es(1).xls', sep = ';', decimal=',')

In [72]:
df.shape

(10064, 24)

In [73]:
df.dtypes

Fecha:              object
04/07/2017 23:00    object
Unnamed: 2          object
Unnamed: 3          object
Unnamed: 4          object
Unnamed: 5          object
Unnamed: 6          object
Unnamed: 7          object
Unnamed: 8          object
Unnamed: 9          object
Unnamed: 10         object
Unnamed: 11         object
Unnamed: 12         object
Unnamed: 13         object
Unnamed: 14         object
Unnamed: 15         object
Unnamed: 16         object
Unnamed: 17         object
Unnamed: 18         object
Unnamed: 19         object
Unnamed: 20         object
Unnamed: 21         object
Unnamed: 22         object
Unnamed: 23         object
dtype: object

In [74]:
df.isnull().sum()

Fecha:                  0
04/07/2017 23:00        0
Unnamed: 2              2
Unnamed: 3              2
Unnamed: 4              5
Unnamed: 5              2
Unnamed: 6              3
Unnamed: 7              3
Unnamed: 8            489
Unnamed: 9            127
Unnamed: 10          7610
Unnamed: 11         10050
Unnamed: 12          2893
Unnamed: 13          9995
Unnamed: 14         10063
Unnamed: 15         10063
Unnamed: 16          3572
Unnamed: 17         10021
Unnamed: 18         10043
Unnamed: 19          9552
Unnamed: 20             2
Unnamed: 21             2
Unnamed: 22             2
Unnamed: 23             2
dtype: int64

In [75]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
10034    False
10035    False
10036    False
10037    False
10038    False
10039    False
10040    False
10041    False
10042    False
10043    False
10044    False
10045    False
10046    False
10047    False
10048    False
10049    False
10050    False
10051    False
10052    False
10053    False
10054    False
10055    False
10056    False
10057    False
10058    False
10059    False
10060    False
10061    False
10062    False
10063    False
dtype: bool

In [76]:
df.head()

,Fecha:,04/07/2017 23:00,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,Descripción:,Archivo de todos los productos en todas las es...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Siglas:,"Margen - D: Derecho, I: Izquierdo, N: No aplic...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Provincia,Municipio,Localidad,Código postal,Dirección,Margen,Longitud,Latitud,Precio gasolina 95,Precio gasóleo A,...,% éster metílico,% bioalcohol,Precio gasolina 98,Precio gas natural comprimido,Precio gas natural licuado,Precio gases licuados del petróleo,Rótulo,Tipo venta,Rem.,Horario
3,ÁLAVA,ALEGRÍA-DULANTZI,ALEGRIA-DULANTZI,01240,"CL MANISITU, 9",D,-2.509361,42.846028,NaN,1.049,...,NaN,NaN,NaN,NaN,NaN,NaN,REPSOL,P,dm,L-D: 24H
4,ÁLAVA,AMURRIO,LARRINBE,01468,"POLIGONO ZANKUETA, 0",D,-2.989111,43.044333,1.119,0.979,...,NaN,NaN,1.229,NaN,NaN,NaN,ESTACIONES GB,P,dm,L-D: 24H

In [77]:
df.drop([0,1,0],axis=0,inplace=True)

In [78]:
df.head()

,Fecha:,04/07/2017 23:00,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
2,Provincia,Municipio,Localidad,Código postal,Dirección,Margen,Longitud,Latitud,Precio gasolina 95,Precio gasóleo A,...,% éster metílico,% bioalcohol,Precio gasolina 98,Precio gas natural comprimido,Precio gas natural licuado,Precio gases licuados del petróleo,Rótulo,Tipo venta,Rem.,Horario
3,ÁLAVA,ALEGRÍA-DULANTZI,ALEGRIA-DULANTZI,01240,"CL MANISITU, 9",D,-2.509361,42.846028,NaN,1.049,...,NaN,NaN,NaN,NaN,NaN,NaN,REPSOL,P,dm,L-D: 24H
4,ÁLAVA,AMURRIO,LARRINBE,01468,"POLIGONO ZANKUETA, 0",D,-2.989111,43.044333,1.119,0.979,...,NaN,NaN,1.229,NaN,NaN,NaN,ESTACIONES GB,P,dm,L-D: 24H
5,ÁLAVA,AMURRIO,LEZAMA,01450,"CARRETERA A-624 KM. 37,8",D,-2.967611,43.031889,1.169,1.053,...,NaN,NaN,1.284,NaN,NaN,NaN,CEPSA,P,OM,L-D: 06:00-22:00
6,ÁLAVA,ARRAIA-MAEZTU,MAEZTU/MAESTU,01120,CARRETERA A-132 VITORIA-ESTELLA KM. 23,I,-2.477917,42.753194,1.145,0.995,...,NaN,NaN,1.235,NaN,NaN,NaN,(SIN RÓTULO),P,dm,L-D: 07:00-23:00

In [79]:
df.drop(['Unnamed: 2','Unnamed: 5','Unnamed: 6','Unnamed: 7'],axis=1,inplace=True)
df.drop(['Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19','Unnamed: 21','Unnamed: 22','Unnamed: 23'],
        axis=1,inplace= True)

In [80]:
df.rename(columns={'Fecha:':'Provincia','Precio':'Precio_Gasolina_95','Unnamed: 10':'Precio_Gasoleo_B','Precio_bioetanol':'Precio gasóleo B',
                   'Unnamed: 11':'Precio_bioetanol','Unnamed: 20':'Petrolera'},inplace=True)

In [54]:
df.head()

,Provincia,04/07/2017 23:00,Unnamed: 3,Unnamed: 4,Unnamed: 8,Unnamed: 9,Precio_Gasoleo_B,Precio_bioetanol,Unnamed: 12,Unnamed: 13,Petrolera
2,Provincia,Municipio,Código postal,Dirección,Precio gasolina 95,Precio gasóleo A,Precio gasóleo B,Precio bioetanol,Precio nuevo gasóleo A,Precio biodiesel,Rótulo
3,ÁLAVA,ALEGRÍA-DULANTZI,01240,"CL MANISITU, 9",NaN,1.049,0.726,NaN,NaN,NaN,REPSOL
4,ÁLAVA,AMURRIO,01468,"POLIGONO ZANKUETA, 0",1.119,0.979,NaN,NaN,1.069,NaN,ESTACIONES GB
5,ÁLAVA,AMURRIO,01450,"CARRETERA A-624 KM. 37,8",1.169,1.053,NaN,NaN,1.113,NaN,CEPSA
6,ÁLAVA,ARRAIA-MAEZTU,01120,CARRETERA A-132 VITORIA-ESTELLA KM. 23,1.145,0.995,NaN,NaN,NaN,NaN,(SIN RÓTULO)

In [55]:
list(df.columns)

['Provincia',
 u'04/07/2017 23:00',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 8',
 'Unnamed: 9',
 'Precio_Gasoleo_B',
 'Precio_bioetanol',
 'Unnamed: 12',
 'Unnamed: 13',
 'Petrolera']

In [56]:
df.isnull().sum()

Provincia               0
04/07/2017 23:00        0
Unnamed: 3              0
Unnamed: 4              3
Unnamed: 8            487
Unnamed: 9            125
Precio_Gasoleo_B     7608
Precio_bioetanol    10048
Unnamed: 12          2891
Unnamed: 13          9993
Petrolera               0
dtype: int64

In [81]:
df.drop(['04/07/2017 23:00','Precio_Gasoleo_B','Precio_bioetanol','Unnamed: 12','Unnamed: 13',
         'Unnamed: 3'],axis=1,inplace=True)

In [82]:
df.head()

,Provincia,Unnamed: 4,Unnamed: 8,Unnamed: 9,Petrolera
2,Provincia,Dirección,Precio gasolina 95,Precio gasóleo A,Rótulo
3,ÁLAVA,"CL MANISITU, 9",NaN,1.049,REPSOL
4,ÁLAVA,"POLIGONO ZANKUETA, 0",1.119,0.979,ESTACIONES GB
5,ÁLAVA,"CARRETERA A-624 KM. 37,8",1.169,1.053,CEPSA
6,ÁLAVA,CARRETERA A-132 VITORIA-ESTELLA KM. 23,1.145,0.995,(SIN RÓTULO)

In [83]:
df.rename(columns={'Unnamed: 4':'Direccion','Unnamed: 8':'Precio_Gasolina_95','Unnamed: 9':'Precio_Gasoleo_A'},inplace=True)

In [84]:
df.drop(df.index[0],axis=0,inplace=True)

In [85]:
df.head()

,Provincia,Direccion,Precio_Gasolina_95,Precio_Gasoleo_A,Petrolera
3,ÁLAVA,"CL MANISITU, 9",NaN,1.049,REPSOL
4,ÁLAVA,"POLIGONO ZANKUETA, 0",1.119,0.979,ESTACIONES GB
5,ÁLAVA,"CARRETERA A-624 KM. 37,8",1.169,1.053,CEPSA
6,ÁLAVA,CARRETERA A-132 VITORIA-ESTELLA KM. 23,1.145,0.995,(SIN RÓTULO)
7,ÁLAVA,AUTOVIA N-1 km 358,1.169,1.059,AVIA

In [86]:
df = df.dropna(subset=['Precio_Gasolina_95'])
df = df.dropna(subset=['Precio_Gasoleo_A'])

In [87]:
df['Precio_Gasolina_95']=df.Precio_Gasolina_95.astype(float)
df['Precio_Gasoleo_A']=df.Precio_Gasoleo_A.astype(float)

In [88]:
#Agrupamos por Provincia

df_p = df.groupby('Provincia',as_index=False).Precio_Gasolina_95.agg(['max','min','mean'])
df_d=df.groupby('Provincia',as_index=False).Precio_Gasoleo_A.agg(['max','min','mean'])

In [89]:
#Clasificación Precios Gasolina 95 por Provincias

df_p.sort_values(by='mean',ascending = False)

                          max    min      mean
Provincia
BALEARS (ILLES)         1.285  1.129  1.237144
CORUÑA (A)              1.319  1.095  1.210607
ASTURIAS                1.358  1.109  1.209005
PONTEVEDRA              1.259  1.139  1.206988
OURENSE                 1.249  1.125  1.204655
MÁLAGA                  1.299  1.079  1.204394
CUENCA                  1.289  1.087  1.202827
CÁDIZ                   1.304  1.105  1.196183
ALBACETE                1.309  1.079  1.195895
GUADALAJARA             1.298  1.099  1.195725
LUGO                    1.239  1.119  1.194692
ALICANTE                1.254  1.019  1.193158
JAÉN                    1.335  1.099  1.192625
HUELVA                  1.242  1.109  1.191198
GRANADA                 1.339  1.095  1.185815
SEVILLA                 1.259  1.077  1.184612
TARRAGONA               1.259  1.058  1.184381
MURCIA                  1.270  1.059  1.184317
CÓRDOBA                 1.245  1.059  1.181837
GIRONA                  1.259  1.055  1.181394
CÁCERES                 1.225  1.089  1.180162
VALENCIA / VALÈNCIA     1.409  1.020  1.179850
TOLEDO                  1.279  1.057  1.179571
ALMERÍA                 1.259  1.056  1.179023
CASTELLÓN / CASTELLÓ    1.269  1.059  1.178210
BARCELONA               1.299  1.044  1.176009
TERUEL                  1.219  1.079  1.174364
CIUDAD REAL             1.319  1.085  1.174133
BADAJOZ                 1.300  1.080  1.171735
HUESCA                  1.219  1.033  1.162236
MADRID                  1.228  1.047  1.162207
LLEIDA                  1.248  1.058  1.161386
ZARAGOZA                1.255  1.035  1.160220
CANTABRIA               1.195  1.059  1.155346
ÁLAVA                   1.199  1.070  1.155000
GUIPÚZCOA               1.219  1.054  1.154430
ÁVILA                   1.219  1.089  1.154098
VIZCAYA                 1.199  1.037  1.146464
RIOJA (LA)              1.185  1.049  1.145873
NAVARRA                 1.259  1.036  1.140680
ZAMORA                  1.189  1.063  1.139811
BURGOS                  1.190  1.059  1.137931
SALAMANCA               1.229  1.049  1.135914
SEGOVIA                 1.199  1.079  1.135409
SORIA                   1.219  1.069  1.135400
LEÓN                    1.209  1.075  1.135048
VALLADOLID              1.228  1.073  1.134893
PALENCIA                1.169  1.079  1.132875
PALMAS (LAS)            1.029  0.894  0.944095
CEUTA                   0.949  0.923  0.941889
SANTA CRUZ DE TENERIFE  1.051  0.779  0.910005
MELILLA                 0.845  0.840  0.842308

In [68]:
##Clasificación Precios Gasóleo A por Provincias
df_d.sort_values(by='mean',ascending = False)

                          max    min      mean
Provincia
BALEARS (ILLES)         1.157  0.999  1.107080
GUADALAJARA             1.168  0.987  1.092387
CORUÑA (A)              1.189  0.975  1.083631
OURENSE                 1.119  0.989  1.083264
PONTEVEDRA              1.119  0.998  1.082125
CUENCA                  1.139  0.938  1.082010
LUGO                    1.129  0.978  1.078215
MÁLAGA                  1.169  0.939  1.073718
ALBACETE                1.196  0.939  1.071710
HUELVA                  1.127  0.989  1.069645
JAÉN                    1.222  0.979  1.068506
ALICANTE                1.149  0.919  1.067210
CIUDAD REAL             1.199  0.955  1.065497
CÁDIZ                   1.131  0.967  1.065018
TOLEDO                  1.149  0.919  1.061977
ASTURIAS                1.199  0.946  1.061756
GIRONA                  1.149  0.895  1.061610
CÁCERES                 1.119  0.979  1.059906
TARRAGONA               1.139  0.919  1.056905
CÓRDOBA                 1.105  0.945  1.053674
ALMERÍA                 1.100  0.928  1.052305
BARCELONA               1.189  0.909  1.051932
SEVILLA                 1.120  0.947  1.050896
GRANADA                 1.249  0.929  1.050718
TERUEL                  1.079  0.919  1.050345
BADAJOZ                 1.190  0.920  1.048355
CASTELLÓN / CASTELLÓ    1.129  0.929  1.046988
MURCIA                  1.139  0.929  1.046045
GUIPÚZCOA               1.085  0.929  1.045991
VALENCIA / VALÈNCIA     1.269  0.947  1.045232
MADRID                  1.119  0.909  1.042274
ZARAGOZA                1.135  0.899  1.041542
LLEIDA                  1.141  0.928  1.040513
HUESCA                  1.109  0.904  1.034673
ÁLAVA                   1.079  0.910  1.033786
VIZCAYA                 1.085  0.917  1.030714
CANTABRIA               1.069  0.919  1.030377
ÁVILA                   1.129  0.949  1.027115
ZAMORA                  1.069  0.915  1.026595
PALENCIA                1.069  0.969  1.024469
VALLADOLID              1.068  0.944  1.023719
BURGOS                  1.069  0.899  1.021267
RIOJA (LA)              1.059  0.889  1.019549
LEÓN                    1.049  0.925  1.019377
SALAMANCA               1.059  0.889  1.015548
SEGOVIA                 1.099  0.929  1.014227
NAVARRA                 1.089  0.897  1.014094
SORIA                   1.129  0.919  1.012886
PALMAS (LAS)            0.922  0.798  0.846286
CEUTA                   0.855  0.826  0.845444
SANTA CRUZ DE TENERIFE  0.985  0.719  0.820350
MELILLA                 0.720  0.715  0.717308

In [91]:
#EESS Gasolina 95 más cara en Madrid:
est_mad=df[df.Provincia=='MADRID']
est_mad.sort_values('Precio_Gasolina_95',ascending=False)

,Provincia,Direccion,Precio_Gasolina_95,Precio_Gasoleo_A,Petrolera
5559,MADRID,N-1 km 87,1.228,1.089,Q8
5669,MADRID,"AVENIDA VENTISQUERO DE LA CONDESA,",1.219,1.099,REPSOL
5801,MADRID,"AU R-2 ,P.K. 35,5 M.I.",1.215,1.099,REPSOL
5584,MADRID,"AUTOPISTA AUTOPISTA R-3 LOECHES KM. 19,5",1.215,1.099,REPSOL
5840,MADRID,"CR R-5 ,P.K. 24,5",1.215,1.099,REPSOL
5841,MADRID,"CR R-5 ,P.K. 24,5",1.215,1.099,REPSOL
5575,MADRID,"CARRETERA R-5 KM. 5,5",1.215,1.099,REPSOL
5574,MADRID,"CARRETERA R-5 KM. 5,5",1.215,1.099,REPSOL
5583,MADRID,"AUTOPISTA AUTOPISTA R-3 LOECHES KM. 19,5",1.215,1.099,REPSOL
5800,MADRID,"AU R-2 ,P.K. 35,5 M.D.",1.215,1.099,REPSOL
5737,MADRID,"CALLE CARDENAL HERRERA ORIA, 81",1.214,1.073,CEPSA
5730,MADRID,"GLORIETA MARIANO SALVADOR MAELLA, S/N",1.214,1.073,CEPSA
5772,MADRID,"CALLE SINESIO DELGADO, 15",1.211,1.068,GALP
5794,MADRID,"CALLE MANUEL DE FALLA, 2",1.209,1.099,REPSOL
5775,MADRID,"CALLE BRAVO MURILLO, 229",1.208,1.073,GALP
5608,MADRID,CARRETERA DE LA CORUÑA KM 12 KM.,1.208,1.097,REPSOL
5808,MADRID,CTRA: M-218 ESQ. C/ DUERO - POLÍGONO INDUSTRIAL,1.204,1.054,GALP
5714,MADRID,"CALLE ANTONIO MACHADO, S/N",1.204,1.064,CEPSA
5771,MADRID,Niceto Alcalá Zamora 20,1.204,1.074,GALP
6006,MADRID,"CARRETERA ALCALA-PASTRANA KM. 4,400",1.203,1.053,JULIO MUÑOZ
5633,MADRID,"AVENIDA MONFORTE DE LEMOS, 10",1.199,1.069,REPSOL
5670,MADRID,"SAN GENJO, 2",1.199,1.069,REPSOL
5648,MADRID,"CALLE FUENTE CARRANTONA S/N, 6",1.199,1.069,REPSOL
5817,MADRID,"CAMINO LOS LINARES, S/N",1.199,1.079,MORALZARZAL
5647,MADRID,"AVENIDA ENTREVIAS, S/N",1.199,1.069,REPSOL
5646,MADRID,"AVENIDA AVENIDA DE MORATALAZ, 21",1.199,1.069,REPSOL
5644,MADRID,"CALLE FRANCOS RODRIGUEZ, SN",1.199,1.069,CAMPSA
5642,MADRID,"CALLE BRAVO MURILLO, 012",1.199,1.069,REPSOL
5634,MADRID,"PASEO SAN FRANCISCO DE SALES, 44",1.199,1.069,REPSOL
5560,MADRID,"CALLE AMADEO VIVES, 2",1.199,1.079,CEPSA
...,...,...,...,...,...
5990,MADRID,"RONDA COMUNIDADES (DE LAS), 107",1.078,0.978,LAS PALMERAS
5855,MADRID,"AVENIDA RONDA (DE), S/N",1.077,0.927,PETROPRIX
5517,MADRID,"CALLE CONSTITUCION, 81",1.077,0.967,BALLENOIL
5857,MADRID,"CALLE TOLEDO CV VIA DE RONDA, SN",1.077,0.927,BALLENOIL
5455,MADRID,"CALLE DEL CEDRO, 5",1.069,0.929,SIMPLY
5998,MADRID,"AVENIDA MADRID (DE), 6",1.069,0.959,GALP
5514,MADRID,"CALLE LUIS SAUQUILLO, 131",1.068,0.938,PLENOIL
5942,MADRID,"AVENIDA FUENTE NUEVA, 18",1.068,0.968,PETROPRIX
5898,MADRID,"CALLE CINCEL (DEL), 2",1.068,0.968,PETROPRIX
5391,MADRID,"CALLE PARAGUAY ESQUINA AVENIDA DE AMERICA, SN",1.068,0.968,PETROPRIX
5806,MADRID,"CALLE PORTUGAL, 30",1.068,0.968,PETROPRIX
5470,MADRID,"AVENIDA JUAN CARLOS I, 24",1.068,0.968,PETROPRIX
5900,MADRID,"CALLE FUNDICION, 19",1.068,0.968,BALLENOIL
5899,MADRID,"CALLE CINCEL (DEL), S",1.068,0.968,BALLENOIL
5432,MADRID,"CAMINO SAN MARTIN DE LA VEGA, 8",1.067,0.947,BALLENOIL
5768,MADRID,"CAMINO POZO DEL TIO RAIMUNDO, 6",1.067,0.947,BALLENOIL
5763,MADRID,"CALLE CALDERILLA, 1",1.057,0.919,E.LECLERC
5513,MADRID,CARRETERA M-506 KM. 21,1.057,0.956,GASOLOWCOST
5421,MADRID,"PASEO DELEITE (DEL), 13",1.057,0.919,E.LECLERC
5988,MADRID,"AVENIDA ANDALUCIA (DE), 118",1.057,0.919,E. LECLERC
5430,MADRID,"AVENIDA MADRID (DE), SN",1.057,0.957,PETROPRIX
5824,MADRID,"CALLE TORRES QUEVEDO, 6",1.057,0.927,PETROL MÓSTOLES
5849,MADRID,"CALLE NANTES, 119",1.057,0.919,E.LECLERC
5876,MADRID,"CALLE PABLO PICASSO, SN",1.057,0.919,E.LECLERC
5508,MADRID,"AVENIDA DE LA CANTUEÑA, 8",1.057,0.957,PETROPRIX
5518,MADRID,"CALLE ANETO, 1",1.057,0.927,BALLENOIL
5540,MADRID,"CALLE AGUSTIN DE BETANCOURT, 17",1.049,0.913,COSTCO
5856,MADRID,"AVENIDA CERRO DEL RUBAL, 12",1.049,0.909,SERVIFACIL
5512,MADRID,CC. LORANCA ALCAMPO FUENLABRADA (AV. PABLO IGL...,1.047,0.917,ALCAMPO FUENLABRADA
5399,MADRID,"AVENIDA EUROPA, S/N",1.047,0.917,ALCAMPO

In [92]:
 #EESS Gasóleo A más cara en Madrid:
est_mad=df[df.Provincia=='MADRID']
est_mad.sort_values('Precio_Gasoleo_A',ascending=False)

,Provincia,Direccion,Precio_Gasolina_95,Precio_Gasoleo_A,Petrolera
5366,MADRID,"PLAZA MORALEJA S/N, S/N",1.199,1.119,REPSOL
5801,MADRID,"AU R-2 ,P.K. 35,5 M.I.",1.215,1.099,REPSOL
5840,MADRID,"CR R-5 ,P.K. 24,5",1.215,1.099,REPSOL
5800,MADRID,"AU R-2 ,P.K. 35,5 M.D.",1.215,1.099,REPSOL
5632,MADRID,"AVENIDA VICTORIA, 34",1.199,1.099,REPSOL
5574,MADRID,"CARRETERA R-5 KM. 5,5",1.215,1.099,REPSOL
5575,MADRID,"CARRETERA R-5 KM. 5,5",1.215,1.099,REPSOL
5977,MADRID,"CALLE CAMINO DE VALLADOLID, 1",1.195,1.099,CAMPSA
5669,MADRID,"AVENIDA VENTISQUERO DE LA CONDESA,",1.219,1.099,REPSOL
5583,MADRID,"AUTOPISTA AUTOPISTA R-3 LOECHES KM. 19,5",1.215,1.099,REPSOL
5584,MADRID,"AUTOPISTA AUTOPISTA R-3 LOECHES KM. 19,5",1.215,1.099,REPSOL
5976,MADRID,"CR A-6, 28,2",1.195,1.099,REPSOL
5792,MADRID,"CL DR.MARAÑON C/V PL ESCORIAL, S.N.",1.199,1.099,REPSOL
5892,MADRID,CARRETERA CARABANCHEL M-502 KM. 3600,1.199,1.099,REPSOL
5793,MADRID,"CARRETERA DEL PLANTIO Nº66 KM. 1,2",1.199,1.099,REPSOL
5794,MADRID,"CALLE MANUEL DE FALLA, 2",1.209,1.099,REPSOL
5841,MADRID,"CR R-5 ,P.K. 24,5",1.215,1.099,REPSOL
5608,MADRID,CARRETERA DE LA CORUÑA KM 12 KM.,1.208,1.097,REPSOL
5620,MADRID,"CL NUESTRA SE¿ORA DE VALVERDE, 175",1.179,1.089,REPSOL
5559,MADRID,N-1 km 87,1.228,1.089,Q8
5882,MADRID,"CARRETERA M-503 VÍA DE LAS DOS CASTILLAS KM. 6,3",1.199,1.089,BP-POZUELO 4
5885,MADRID,"AVENIDA RADIO TELEVISION ESPAÑOLA, 1",1.199,1.089,BP SOMOSAGUAS
5682,MADRID,"CALLE ABETAL, 8",1.179,1.089,REPSOL
5525,MADRID,"AUTOVIA A-3 KM. 62,5",1.195,1.085,REPSOL
5864,MADRID,"AUTOVIA E-901/A-3 KM. 35,2",1.195,1.085,REPSOL
5795,MADRID,"CALLE SARASATE, 1",1.199,1.084,BP RELAMPAGO
5745,MADRID,"CALLE SANTO DOMINGO, 10",1.179,1.081,SHELL
5905,MADRID,"CR A-6, 20,3",1.199,1.079,REPSOL
5498,MADRID,"AVENIDA SAN PABLO, 32",1.179,1.079,REPSOL
5439,MADRID,"CALLE CONDESA DE CHINCHÓN, 37",1.184,1.079,GALP
...,...,...,...,...,...
5470,MADRID,"AVENIDA JUAN CARLOS I, 24",1.068,0.968,PETROPRIX
5507,MADRID,"CALLE CONSTITUCION (DE LA), 100",1.078,0.968,PETROPRIX
5900,MADRID,"CALLE FUNDICION, 19",1.068,0.968,BALLENOIL
5899,MADRID,"CALLE CINCEL (DEL), S",1.068,0.968,BALLENOIL
5898,MADRID,"CALLE CINCEL (DEL), 2",1.068,0.968,PETROPRIX
5517,MADRID,"CALLE CONSTITUCION, 81",1.077,0.967,BALLENOIL
5998,MADRID,"AVENIDA MADRID (DE), 6",1.069,0.959,GALP
5509,MADRID,"CALLE ALMANZOR, 11",1.079,0.959,MR.GAS
5750,MADRID,CARRETERA VILLAVERDE A VALLECAS KM. 267,1.078,0.958,PLENOIL
5423,MADRID,"AVENIDA MADRID (DE), 66",1.078,0.958,PLENOIL
5430,MADRID,"AVENIDA MADRID (DE), SN",1.057,0.957,PETROPRIX
5508,MADRID,"AVENIDA DE LA CANTUEÑA, 8",1.057,0.957,PETROPRIX
5513,MADRID,CARRETERA M-506 KM. 21,1.057,0.956,GASOLOWCOST
5432,MADRID,"CAMINO SAN MARTIN DE LA VEGA, 8",1.067,0.947,BALLENOIL
5768,MADRID,"CAMINO POZO DEL TIO RAIMUNDO, 6",1.067,0.947,BALLENOIL
5514,MADRID,"CALLE LUIS SAUQUILLO, 131",1.068,0.938,PLENOIL
5455,MADRID,"CALLE DEL CEDRO, 5",1.069,0.929,SIMPLY
5857,MADRID,"CALLE TOLEDO CV VIA DE RONDA, SN",1.077,0.927,BALLENOIL
5518,MADRID,"CALLE ANETO, 1",1.057,0.927,BALLENOIL
5855,MADRID,"AVENIDA RONDA (DE), S/N",1.077,0.927,PETROPRIX
5824,MADRID,"CALLE TORRES QUEVEDO, 6",1.057,0.927,PETROL MÓSTOLES
5763,MADRID,"CALLE CALDERILLA, 1",1.057,0.919,E.LECLERC
5988,MADRID,"AVENIDA ANDALUCIA (DE), 118",1.057,0.919,E. LECLERC
5876,MADRID,"CALLE PABLO PICASSO, SN",1.057,0.919,E.LECLERC
5421,MADRID,"PASEO DELEITE (DEL), 13",1.057,0.919,E.LECLERC
5849,MADRID,"CALLE NANTES, 119",1.057,0.919,E.LECLERC
5512,MADRID,CC. LORANCA ALCAMPO FUENLABRADA (AV. PABLO IGL...,1.047,0.917,ALCAMPO FUENLABRADA
5399,MADRID,"AVENIDA EUROPA, S/N",1.047,0.917,ALCAMPO
5540,MADRID,"CALLE AGUSTIN DE BETANCOURT, 17",1.049,0.913,COSTCO
5856,MADRID,"AVENIDA CERRO DEL RUBAL, 12",1.049,0.909,SERVIFACIL

In [93]:
df.groupby(['Petrolera','Provincia'],as_index=False).Precio_Gasoleo_A.agg(['max','min','mean'])

                                                              max    min  \
Petrolera                           Provincia
   PETROL STATION                   CÁCERES                 0.999  0.999
 AGLA                               GRANADA                 1.069  1.069
 AGRICAR                            VALENCIA / VALÈNCIA     1.039  1.039
 BP AVENIDA 3 DE MAYO               SANTA CRUZ DE TENERIFE  0.849  0.849
 BP RAMBLA INIESTA                  ALMERÍA                 1.100  1.100
 BP SANTIGA                         BARCELONA               1.069  1.069
 BP TACO                            SANTA CRUZ DE TENERIFE  0.809  0.809
 E.S. LA TORRETA                    VALENCIA / VALÈNCIA     1.059  1.059
 E.S. SUR                           VALENCIA / VALÈNCIA     1.059  1.059
 EA SANTA POLA                      ALICANTE                1.086  1.086
 LAS GABIAS                         GRANADA                 0.985  0.985
 OCTAPLUS                           VALENCIA / VALÈNCIA     0.978  0.978
 SHELL                              CANTABRIA               1.029  1.029
 SUTULLENA-CEPSA                    MURCIA                  1.069  1.069
 T. ALBERO                          ALICANTE                1.059  1.059
"E.S. EL CAMPILLO" (AGLA, RIOGORDO) MÁLAGA                  0.999  0.999
(SIN RÓTULO)                        ALICANTE                1.089  1.039
                                    ALMERÍA                 1.077  1.077
                                    BADAJOZ                 1.049  1.049
                                    BARCELONA               0.979  0.979
                                    CANTABRIA               0.989  0.989
                                    CÁCERES                 1.089  1.089
                                    JAÉN                    1.200  1.200
                                    LEÓN                    1.029  1.029
                                    MÁLAGA                  1.055  1.055
                                    OURENSE                 1.088  1.088
                                    PALMAS (LAS)            0.899  0.899
                                    SEVILLA                 1.019  1.019
                                    VALENCIA / VALÈNCIA     1.269  1.002
                                    VALLADOLID              1.039  1.039
...                                                           ...    ...
VILALTA                             BARCELONA               1.009  1.009
VILAMARXANT                         VALENCIA / VALÈNCIA     1.079  1.079
VILLA RUBEUM,S.L.                   CIUDAD REAL             1.059  1.059
VILLAGER                            LEÓN                    0.979  0.979
VILLALONQUEJAR                      BURGOS                  1.043  1.043
VILLALÓN                            BURGOS                  1.019  1.019
VILLANUEVA, C.B. BP                 VALENCIA / VALÈNCIA     1.059  1.059
VILOBI                              GIRONA                  1.079  1.079
VIRGEN DE LA CORONA                 HUESCA                  0.930  0.930
VISTAHERMOSA                        ALICANTE                1.084  1.084
VIVAR DEL CID                       BURGOS                  1.018  1.018
VULCO                               ALMERÍA                 1.049  1.049
WASHMAX                             ASTURIAS                1.069  1.069
WENCES                              BARCELONA               0.959  0.959
WETROAD                             CIUDAD REAL             1.009  1.009
WINDFUEL TARIFA LOW COST            CÁDIZ                   1.029  1.029
XOPLUC-PETROMIRALLES                LLEIDA                  0.988  0.988
YENO                                VALENCIA / VALÈNCIA     0.959  0.959
YETHI                               CORUÑA (A)              1.039  1.039
ZACATÍN                             SEVILLA                 0.999  0.999
ZARCAR                              ALICANTE                1.049  1.049
ZENIT SOTOGALO                      RIOJA (LA)              0.989  0.989
ZEROGAS                             MADRID                  0.999  0.999
ZOIL                                TOLEDO                  1.059  1.059
ZOIL J.C.M. GASOLINERAS S.L.        TOLEDO                  1.059  1.059
ZONA DIESEL                         BARCELONA               0.929  0.929
                                    GIRONA                  0.979  0.979
ZONA DIESEL                         BARCELONA               0.999  0.999
                                    GIRONA                  0.969  0.969
ZUFRE SERVICIOS E.S.C               HUELVA                  1.127  1.127

                                                                mean
Petrolera                           Provincia
   PETROL STATION                   CÁCERES                 0.999000
 AGLA                               GRANADA                 1.069000
 AGRICAR                            VALENCIA / VALÈNCIA     1.039000
 BP AVENIDA 3 DE MAYO               SANTA CRUZ DE TENERIFE  0.849000
 BP RAMBLA INIESTA                  ALMERÍA                 1.100000
 BP SANTIGA                         BARCELONA               1.069000
 BP TACO                            SANTA CRUZ DE TENERIFE  0.809000
 E.S. LA TORRETA                    VALENCIA / VALÈNCIA     1.059000
 E.S. SUR                           VALENCIA / VALÈNCIA     1.059000
 EA SANTA POLA                      ALICANTE                1.086000
 LAS GABIAS                         GRANADA                 0.985000
 OCTAPLUS                           VALENCIA / VALÈNCIA     0.978000
 SHELL                              CANTABRIA               1.029000
 SUTULLENA-CEPSA                    MURCIA                  1.069000
 T. ALBERO                          ALICANTE                1.059000
"E.S. EL CAMPILLO" (AGLA, RIOGORDO) MÁLAGA                  0.999000
(SIN RÓTULO)                        ALICANTE                1.064000
                                    ALMERÍA                 1.077000
                                    BADAJOZ                 1.049000
                                    BARCELONA               0.979000
                                    CANTABRIA               0.989000
                                    CÁCERES                 1.089000
                                    JAÉN                    1.200000
                                    LEÓN                    1.029000
                                    MÁLAGA                  1.055000
                                    OURENSE                 1.088000
                                    PALMAS (LAS)            0.899000
                                    SEVILLA                 1.019000
                                    VALENCIA / VALÈNCIA     1.136667
                                    VALLADOLID              1.039000
...                                                              ...
VILALTA                             BARCELONA               1.009000
VILAMARXANT                         VALENCIA / VALÈNCIA     1.079000
VILLA RUBEUM,S.L.                   CIUDAD REAL             1.059000
VILLAGER                            LEÓN                    0.979000
VILLALONQUEJAR                      BURGOS                  1.043000
VILLALÓN                            BURGOS                  1.019000
VILLANUEVA, C.B. BP                 VALENCIA / VALÈNCIA     1.059000
VILOBI                              GIRONA                  1.079000
VIRGEN DE LA CORONA                 HUESCA                  0.930000
VISTAHERMOSA                        ALICANTE                1.084000
VIVAR DEL CID                       BURGOS                  1.018000
VULCO                               ALMERÍA                 1.049000
WASHMAX                             ASTURIAS                1.069000
WENCES                              BARCELONA               0.959000
WETROAD                             CIUDAD REAL             1.009000
WINDFUEL TARIFA LOW COST            CÁDIZ                   1.029000
XOPLUC-PETROMIRALLES                LLEIDA                  0.988000
YENO                                VALENCIA / VALÈNCIA     0.959000
YETHI                               CORUÑA (A)              1.039000
ZACATÍN                             SEVILLA                 0.999000
ZARCAR                              ALICANTE                1.049000
ZENIT SOTOGALO                      RIOJA (LA)              0.989000
ZEROGAS                             MADRID                  0.999000
ZOIL                                TOLEDO                  1.059000
ZOIL J.C.M. GASOLINERAS S.L.        TOLEDO                  1.059000
ZONA DIESEL                         BARCELONA               0.929000
                                    GIRONA                  0.979000
ZONA DIESEL                         BARCELONA               0.999000
                                    GIRONA                  0.969000
ZUFRE SERVICIOS E.S.C               HUELVA                  1.127000

[3338 rows x 3 columns]

In [95]:
#Comparación Precio Petroleras en España 
df.Petrolera.value_counts()

REPSOL                                              2699
CEPSA                                               1371
GALP                                                 526
SHELL                                                344
PETRONOR                                             207
BP                                                   195
CAMPSA                                               186
CARREFOUR                                            142
AVIA                                                 133
BALLENOIL                                             90
MEROIL                                                51
SARAS                                                 48
BONAREA                                               45
AGLA                                                  43
PETROPRIX                                             41
EROSKI                                                41
ESCLATOIL                                             37
VALCARCE                                              35
IBERDOEX                                              32
DISA                                                  32
ALCAMPO                                               24
PETROCAT                                              24
GASEXPRESS                                            22
(SIN RÓTULO)                                          19
SIMPLY                                                19
TAMOIL                                                18
PETROCAT DIRECTE                                      17
SARAS ENERGIA                                         17
CAMPSA EXPRESS                                        16
PCAN                                                  16
                                                    ...
COAGAL                                                 1
COOP. AGRARIA SAN ISIDRO DE VALL D'ALBA, COOP.V.       1
E.S. REJAS VERDES                                      1
PETROLIS INDEPENDENTS                                  1
AREA CABRERÈS                                          1
A.N. GLUS                                              1
E.S. MONTEVIRGEN                                       1
OROTIANDA                                              1
RAPIDFUEL                                              1
LAS COLONIAS                                           1
BP PRINCESA I                                          1
 BP SANTIGA                                            1
EMBOCADOR                                              1
E.S. LA VENDIMIA                                       1
E.S SANT ISIDRE                                        1
E.S.RUTANCARES S.L.                                    1
BP CARABANCHEL                                         1
SANT QUIRZE 2000                                       1
ARENTO SIERRA DE LUNA                                  1
COOPERATIVA CABANES                                    1
REPSOL - SAN ROMAN                                     1
E.S. EL MOLINO MARACENA                                1
E.S. RED OIL                                           1
LA LANCHA                                              1
VALLIWASH-PETROMIRALLES                                1
BP CRUZ DEL SEÑOR                                      1
DISA TARAHALES I                                       1
HRC                                                    1
LPB                                                    1
BP                                                     1
Name: Petrolera, dtype: int64

In [96]:
import re

In [98]:
df['Petrolera'].replace(r'(\\n)','')

4                  ESTACIONES GB
5                          CEPSA
6                   (SIN RÓTULO)
7                           AVIA
8                          CEPSA
9                          AVIA
10                         CEPSA
12                      PETRONOR
13                        REPSOL
14                       EUROCAM
17                        REPSOL
18                        REPSOL
19                          AVIA
20                      PETRONOR
21                        EROSKI
22                     E.S. OION
23              E.S. TOCALU S.L.
24                         SHELL
25                        EROSKI
26                      PETRONOR
27                      PETRONOR
28                EESS ROMPETROL
29                          GALP
31                        IS-XXI
32           ANDAMUR "SAN ROMAN"
33                        EROSKI
34                        REPSOL
35                        EROSKI
36                         CEPSA
37                         CEPSA
                  ...
10032                      CEPSA
10033                    BONAREA
10034                     LABOIL
10036                       DAGO
10037                     REPSOL
10038                     REPSOL
10039                     REPSOL
10040                     REPSOL
10041                     REPSOL
10042                     REPSOL
10043                      NAFTE
10044                   PETRONOR
10045                     REPSOL
10046                      NAFTE
10047                      NAFTE
10048                      NAFTE
10049                      CEPSA
10050        ES MIRALBUENO CEPSA
10051                      CEPSA
10052                      CEPSA
10053                      CEPSA
10054      COOPERATIVA AUTO-TAXI
10055                     MEROIL
10056                    ALCAMPO
10057                       GALP
10058                       GALP
10059                       GALP
10061                     ARENTO
10062    COOP.SAN LICER - ARENTO
10063                     REPSOL
Name: Petrolera, dtype: object

In [99]:
#Agrupamos bajo una misma marca las distintas denominaciones de las Gasolineras de esa marca. REGEX
df['Petrolera']=df.Petrolera.str.replace(r'(^BP.*$)','BP')
df['Petrolera']=df.Petrolera.str.replace(r'(^REPSOL.*$)','REPSOL')
df['Petrolera']=df.Petrolera.str.replace(r'(^CEPSA.*$)','CEPSA')

In [100]:
df['Petrolera']=df.Petrolera.str.replace(r'(^CAMPSA.*$)','CAMPSA')
df['Petrolera']=df.Petrolera.str.replace(r'(^GALP.*$)','GALP')
df['Petrolera']=df.Petrolera.str.replace(r'(^PETRONOR.*$)','PETRONOR')
df['Petrolera']=df.Petrolera.str.replace(r'(^CARREFOUR.*$)','CARREFOUR')
df['Petrolera']=df.Petrolera.str.replace(r'(^AVIA.*$)','AVIA')
df['Petrolera']=df.Petrolera.str.replace(r'(^BALLENOIL.*$)','BALLENOIL')
df['Petrolera']=df.Petrolera.str.replace(r'(^SARAS.*$)','SARAS')

In [101]:
df['Petrolera']=df.Petrolera.str.replace(r'(^BONAREA.*$)','BONAREA')
df['Petrolera']=df.Petrolera.str.replace(r'(^MEROIL.*$)','MEROIL')
df['Petrolera']=df.Petrolera.str.replace(r'(^EROSKI.*$)','EROSKI')
df['Petrolera']=df.Petrolera.str.replace(r'(^PETROPRIX.*$)','PETROPRIX')
df['Petrolera']=df.Petrolera.str.replace(r'(^ESCLATOIL.*$)','ESCLATOIL')
df['Petrolera']=df.Petrolera.str.replace(r'(^DISA.*$)','DISA')
df['Petrolera']=df.Petrolera.str.replace(r'(^VALCARCE.*$)','VALCARCE')
df['Petrolera']=df.Petrolera.str.replace(r'(^ALCAMPO.*$)','ALCAMPO')
df['Petrolera']=df.Petrolera.str.replace(r'(^IBERDOEX.*$)','IBERDOEX')
df['Petrolera']=df.Petrolera.str.replace(r'(^PETROCAT.*$)','PETROCAT')
df['Petrolera']=df.Petrolera.str.replace(r'(^SIMPLY.*$)','SIMPLY')
df['Petrolera']=df.Petrolera.str.replace(r'(^TAMOIL.*$)','TAMOIL')
df['Petrolera']=df.Petrolera.str.replace(r'(^PETROMIRALLES.*$)','PETROMIRALLES')
df['Petrolera']=df.Petrolera.str.replace(r'(^ELECRERC.*$)','ELECRERC')

In [102]:
df.Petrolera.value_counts()

REPSOL                                              2721
CEPSA                                               1436
GALP                                                 546
BP                                                   437
SHELL                                                344
PETRONOR                                             210
CAMPSA                                               202
AVIA                                                 142
CARREFOUR                                            142
DISA                                                 134
BALLENOIL                                             90
SARAS                                                 84
MEROIL                                                55
BONAREA                                               45
AGLA                                                  43
PETROPRIX                                             41
EROSKI                                                41
PETROCAT                                              41
VALCARCE                                              38
ESCLATOIL                                             38
IBERDOEX                                              33
ALCAMPO                                               31
GASEXPRESS                                            22
(SIN RÓTULO)                                          19
SIMPLY                                                19
TAMOIL                                                18
PCAN                                                  16
PETROMIRALLES                                         16
E.LECLERC                                             13
CONFORT AUTO                                          12
                                                    ...
RAPIDFUEL                                              1
LA GALIA (HNOS AZORIN)                                 1
OROTIANDA                                              1
E.S. MONTEVIRGEN                                       1
A.N. GLUS                                              1
AREA CABRERÈS                                          1
PETROLIS INDEPENDENTS                                  1
E.S. REJAS VERDES                                      1
COOP. AGRARIA SAN ISIDRO DE VALL D'ALBA, COOP.V.       1
COAGAL                                                 1
AMAYVI - II                                            1
SUPERGASOIL                                            1
E.S. CORTIÑAN                                          1
 BP SANTIGA                                            1
EMBOCADOR                                              1
E.S. LA VENDIMIA                                       1
E.S. RED OIL                                           1
LPB                                                    1
HRC                                                    1
VALLIWASH-PETROMIRALLES                                1
LA LANCHA                                              1
E.S. EL MOLINO MARACENA                                1
E.S SANT ISIDRE                                        1
COOPERATIVA CABANES                                    1
ARENTO SIERRA DE LUNA                                  1
SANT QUIRZE 2000                                       1
E.S.RUTANCARES S.L.                                    1
ESTACION DE SERVICIO NOVOMILLADOIRO                    1
AN ENERGÉTICOS SARTAGUDA                               1
AGLA - E.S.VISTA HEMOSA                                1
Name: Petrolera, dtype: int64

In [103]:

df['Petrolera'].replace(' BP SANTIGA','BP',inplace = True)
df['Petrolera'].replace('SHELL VEGUETA','SHELL',inplace=True)

In [104]:
df.Petrolera.value_counts()

REPSOL                                              2721
CEPSA                                               1436
GALP                                                 546
BP                                                   438
SHELL                                                345
PETRONOR                                             210
CAMPSA                                               202
AVIA                                                 142
CARREFOUR                                            142
DISA                                                 134
BALLENOIL                                             90
SARAS                                                 84
MEROIL                                                55
BONAREA                                               45
AGLA                                                  43
PETROPRIX                                             41
EROSKI                                                41
PETROCAT                                              41
ESCLATOIL                                             38
VALCARCE                                              38
IBERDOEX                                              33
ALCAMPO                                               31
GASEXPRESS                                            22
SIMPLY                                                19
(SIN RÓTULO)                                          19
TAMOIL                                                18
PCAN                                                  16
PETROMIRALLES                                         16
E.LECLERC                                             13
BEROIL                                                12
                                                    ...
RAPIDFUEL                                              1
E.S. LOS PAJARES-AGLA                                  1
OROTIANDA                                              1
E.S. MONTEVIRGEN                                       1
A.N. GLUS                                              1
AREA CABRERÈS                                          1
PETROLIS INDEPENDENTS                                  1
E.S. REJAS VERDES                                      1
COOP. AGRARIA SAN ISIDRO DE VALL D'ALBA, COOP.V.       1
COAGAL                                                 1
AMAYVI - II                                            1
SUPERGASOIL                                            1
E.S. CORTIÑAN                                          1
EMBOCADOR                                              1
E.S. LA VENDIMIA                                       1
E.S. RED OIL                                           1
LPB                                                    1
HRC                                                    1
VALLIWASH-PETROMIRALLES                                1
LA LANCHA                                              1
E.S. EL MOLINO MARACENA                                1
E.S SANT ISIDRE                                        1
COOPERATIVA CABANES                                    1
ARENTO SIERRA DE LUNA                                  1
SANT QUIRZE 2000                                       1
E.S.RUTANCARES S.L.                                    1
ESTACION DE SERVICIO NOVOMILLADOIRO                    1
AN ENERGÉTICOS SARTAGUDA                               1
LA GALIA (HNOS AZORIN)                                 1
AGLA - E.S.VISTA HEMOSA                                1
Name: Petrolera, dtype: int64

In [105]:
#Eliminamos las 19 gasolineras con proveedor desconocido.
df.drop(df[df.Petrolera.str.contains('(SIN RÓTULO)')].index,axis = 0,inplace = True)

/home/dsc/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  if __name__ == '__main__':

In [108]:
df.shape

(9550, 5)

In [106]:
#Seleccionamos las Petroleras con más de 12 gasolineras
oil = ['REPSOL','CEPSA','GALP','BP','SHELL','CAMPSA','PETRONOR','AVIA','CARREFOUR','DISA','BALLEMOIL','SARAS','MEROIL','EROSKI',
       'BONAREA','AGLA','PETROCAT','PETROPRIX','ESCLATOIL','VALCARCE','ALCAMPO','IBERDOEX','GASEXPRESS','TAMOIL','SIMPLY','PETROMIRALLES',
       'PCAN','E.LECLERC','BEROIL']
est_marcas = df[df.Petrolera.isin(oil)]

In [107]:
#Se pierden datos de 2638 Gasolineras. Independientes y estaciones de servicio que no muestran que marca distribuyen
est_marcas.shape

(6922, 5)

In [109]:
#Petroleras con Gasóleo más económico de media: 
est_marcas.groupby('Petrolera',as_index=False).Precio_Gasoleo_A.agg(['max','min','mean']).sort_values(by='mean',ascending=True)

                 max    min      mean
Petrolera
PCAN           0.903  0.743  0.814500
DISA           1.069  0.739  0.849784
BONAREA        0.937  0.904  0.925778
ESCLATOIL      0.929  0.929  0.929000
E.LECLERC      0.965  0.915  0.933000
SIMPLY         0.990  0.905  0.945895
ALCAMPO        1.038  0.899  0.961194
EROSKI         1.049  0.910  0.964122
GASEXPRESS     1.029  0.937  0.978591
PETROPRIX      0.988  0.927  0.980122
BEROIL         1.019  0.919  0.985667
TAMOIL         1.089  0.949  1.015611
PETROMIRALLES  1.089  0.969  1.027625
AVIA           1.109  0.929  1.029648
SHELL          1.139  0.720  1.032272
SARAS          1.119  0.939  1.035988
CARREFOUR      1.099  0.959  1.036634
IBERDOEX       1.119  0.945  1.042333
BP             1.129  0.715  1.046096
AGLA           1.099  0.979  1.048070
MEROIL         1.222  0.969  1.052291
GALP           1.189  0.919  1.053456
PETROCAT       1.119  0.939  1.054390
CEPSA          1.149  0.715  1.060631
CAMPSA         1.129  0.919  1.061208
VALCARCE       1.119  0.957  1.063579
PETRONOR       1.139  0.999  1.068819
REPSOL         1.149  0.739  1.071784

In [110]:
# Averiguamos donde se localizan los tres distribuidores de Gasóleo A más económicos : 
#Cataluña,Aragón e Islas Canarias (Fiscal)

baratas =est_marcas[(est_marcas.Petrolera=='DISA') | (est_marcas.Petrolera=='PCAN') | (est_marcas.Petrolera=='BONAREA')]
baratas.groupby(['Petrolera','Provincia'],as_index=False).Precio_Gasoleo_A.mean()

   Petrolera               Provincia  Precio_Gasoleo_A
0    BONAREA               BARCELONA          0.926583
1    BONAREA    CASTELLÓN / CASTELLÓ          0.937000
2    BONAREA                  GIRONA          0.928000
3    BONAREA                  HUESCA          0.904500
4    BONAREA                  LLEIDA          0.930529
5    BONAREA               TARRAGONA          0.930714
6    BONAREA                ZARAGOZA          0.908000
7       DISA                   CEUTA          0.844000
8       DISA                  HUELVA          1.061500
9       DISA            PALMAS (LAS)          0.849776
10      DISA  SANTA CRUZ DE TENERIFE          0.837944
11      PCAN            PALMAS (LAS)          0.854333
12      PCAN  SANTA CRUZ DE TENERIFE          0.805308

In [111]:
#Localización Distribuidores con Gasolina 95 más económica.

Gas =est_marcas[(est_marcas.Petrolera=='DISA') | (est_marcas.Petrolera=='PCAN') | (est_marcas.Petrolera=='BONAREA') |
               (est_marcas.Petrolera=='E.LECLERC')]
Gas.groupby(['Petrolera','Provincia'],as_index=False).Precio_Gasolina_95.mean().sort_values(by='Precio_Gasolina_95',ascending= True)

    Petrolera               Provincia  Precio_Gasolina_95
21       PCAN  SANTA CRUZ DE TENERIFE            0.892846
10       DISA  SANTA CRUZ DE TENERIFE            0.931014
7        DISA                   CEUTA            0.945000
20       PCAN            PALMAS (LAS)            0.947333
9        DISA            PALMAS (LAS)            0.949862
3     BONAREA                  HUESCA            1.033500
6     BONAREA                ZARAGOZA            1.037000
0     BONAREA               BARCELONA            1.055750
19  E.LECLERC                  TOLEDO            1.057000
15  E.LECLERC                  MADRID            1.057000
2     BONAREA                  GIRONA            1.057000
17  E.LECLERC                 NAVARRA            1.060000
4     BONAREA                  LLEIDA            1.060000
5     BONAREA               TARRAGONA            1.060143
18  E.LECLERC               SALAMANCA            1.065000
1     BONAREA    CASTELLÓN / CASTELLÓ            1.066000
12  E.LECLERC                 BADAJOZ            1.080000
13  E.LECLERC                  BURGOS            1.090000
14  E.LECLERC             CIUDAD REAL            1.109000
11  E.LECLERC                ALICANTE            1.117000
16  E.LECLERC                  MURCIA            1.136000
8        DISA                  HUELVA            1.174000